channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pandas
  - bioconda::obonet
  - networkx
  - lxml
  - bioconda::pyteomics
  - pip:
    - requests
    - pyyaml
    - joblib
    - tqdm